 - hosts: PROD 
   become: yes
   tasks: 
     - name: Create a new folder
       ansible.builtin.file: 
        path: /tmp/newfolder3
        state: directory
     - name: create a file
       ansible.builtin.file:
        path: /tmp/newfolder3/filename2
        state: touch 
