---
- name: Using When using registers
  hosts: all
  tasks:
    - name:  Reboot server
      reboot:
        msg: "Server is rebooting"
      when: >
        ansible_facts['distribution'] == "RedHat" or 
        ansible_facts['distribution'] == "CentOS" 
