---
- name: Using files with facts
  hosts: all
  tasks: 
    - name : Detect Ubuntu Servers
      debug:
        msg: "This is Redhat server"
      when: ansible_facts['distribution'] == "RedHat"
    - name : print distrubition
      debug:
        msg: Distribution is {{ ansible_facts['distribution'] }}
