---
- name: working with vairables
  hosts: all  
  tasks:
    - name: Load the variables
      include_vars: myvars.yml

    - name: Show 2nd item in port_nums
      debug:
        msg: SSH port is {{ port_nums[1] }}
    - name: Show the uid of bob
      debug:
        msg: 
          - "UID of bob is {{ users.bob.uid }}"
          - "My Favorite color is {{ fav_color}} "
    - name: display node1 fqdn 
      debug:
        msg: FQDN is {{ ansible_facts.fqdn }}  
    - name: display Distro is
      debug: 
        msg: OS Distro is {{ ansible_facts.distribution }} 

